title:            eyenx
description:      yet another geek
url:              http://eyenx.ch # Site url.
disqus_shortname: eyenx 
twitter_username: eyenx

links:
  - name:         about
    url:          /about
    icon:         fi-torso
  - name:         mail
    url:          mailto:eye@eyenx.ch
    icon:         fi-mail
    external:     true
  - name:         twitter
    url:          https://twitter.com/eyenx 
    icon:         fi-social-twitter
    external:     true
  - name:         github
    url:          https://github.com/eyenx
    icon:         fi-social-github
    external:     true
  - name:         googleplus
    url:          https://google.com/+AntonioTauro
    icon:         fi-social-google-plus
    external:     true
  - name:         lastfm
    url:          https://last.fm/user/gnomeye
    icon:         fi-social-lastfm
    external:     true
  - name:         rss
    url:          /rss.xml
    icon:         fi-rss
highlighter:      pygments
permalink:        /:year/:month/:day/:title
markdown:         kramdown
