version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build image
          command: |
            docker build -t eyenx/eyenx-ch:$(echo -n ${CIRCLE_BRANCH}|tr "/" "-") .
      - run:
          name: run test
          command: |
            docker run -d -p 8080:80 eyenx/eyenx-ch:$(echo -n ${CIRCLE_BRANCH}|tr "/" "-") && sleep 20 && docker exec $(docker ps -q) apk add curl && docker exec $(docker ps -q) curl localhost
      - run:
          name: push image to branch tag
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin && docker push eyenx/eyenx-ch:$(echo -n ${CIRCLE_BRANCH}|tr "/" "-")
      - run:
          name: push image to latest if branch is master
          command: |
            if [ "$CIRCLE_BERANCH" = "master" ] ; then docker tag eyenx/eyenx-ch:$(echo -n ${CIRCLE_BRANCH}|tr "/" "-") eyenx/eyenx-ch:latest &&  echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin && docker push eyenx/eyenx-ch:latest ; fi
  deploy:
    docker:
      - image: alpine
    steps:
      - run:
          name: run trigger to deploy 
          command: |
            apk --update add curl && LAST_BUILD=$(curl -H "Authorization: Bearer $DRONE_TOKEN" https://$DRONE_SERVER/api/repos/eyenx/$DRONE_REPO/builds | grep "number\":[0-9]\+" -o | cut -d: -f2 | head -1) && curl -H "Authorizaiton: Bearer $DRONE_TOKEN" https://$DRONE_SERVER/api/repos/eyenx/$DRONE_REPO/builds/$LAST_BUILD -X POST
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
