version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: |
            docker build -t eyenx/eyenx-ch .
      - run:
          name: Run Tests
          command: |
            docker run -d -p 4000:4000 eyenx/eyenx-ch && sleep 20 && docker exec $(docker ps -q) /test.sh
      - run:
          name: Push Image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin && docker push eyenx/eyenx-ch:latest
