# Site settings
title:          eyenx
description:    "yet another geek"
url:            "https://eyenx.ch"


# Author
author:
  name:         eyenx
  url:          https://eyenx.ch
  email:        eye@eyenx.ch

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink:      /:year/:month/:day/:title/
paginate:       5
#highlighter: pygments

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus
disqus: eyenx

# links
links:
  - name:         mail
    url:          mailto:eye@eyenx.ch
    icon:         fi-mail
  - name:         twitter
    url:          https://twitter.com/eyenx
    icon:         fi-social-twitter
    external:     true
  - name:         github
    url:          https://github.com/eyenx
    icon:         fi-social-github
    external:     true
  - name:         rss
    url:          /rss.xml
    icon:         fi-rss
