name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run go-semantic-release
        id: semrel
        uses: go-semantic-release/action@v1.15
        with:
          github-token: ${{ secrets.PAT }}
          allow-initial-development-versions: true
