name: Bump version
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Run go-semantic-release
        id: semrel
        uses: go-semantic-release/action@8728a77171abeb8438de6ddfe3779626d081c13e # v1.21.1
        with:
          github-token: ${{ secrets.PAT }}
          allow-initial-development-versions: true
