name: "build"
on:
  schedule:
    - cron: '3 3 * * *'
  push:
    branches:
    - 'master'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build and push the image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: eyenx/eyenx-ch
          tag_with_ref: true
          tag_with_sha: true
      - name: trigger deployment
        run: |
          docker run -e DRONE_ARGS=$DRONE_ARGS -e DRONE_TOKEN=$DRONE_TOKEN -e DRONE_SERVER=$DRONE_SERVER eyenx/drone-build-trigger
        env:
          DRONE_SERVER: ${{ secrets.DRONE_SERVER }}
          DRONE_TOKEN: ${{ secrets.DRONE_TOKEN }}
          DRONE_ARGS: "-p DEPLOY=eyenx.ch"



